# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20170913_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='expiration',
            field=models.DateTimeField(db_column='expiration', db_index=True, default=datetime.datetime(2017, 9, 13, 17, 58, 51, 441976)),
            preserve_default=False,
        ),
    ]
