# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0039_auto_20170118_1503'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['field', 'stringValue', 'languageCode'], name='consentreco_fieldid_8ca313_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['field', 'referenceValue'], name='consentreco_fieldid_8c14c9_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['instance', 'field'], name='consentreco_instanc_039ad9_idx'),
        ),
    ]
