# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0040_auto_20170510_0020'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['parent', 'typeID'], name='consentreco_parenti_148121_idx'),
        ),
    ]
