# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:28
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0045_auto_20170521_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('state', models.CharField(db_index=True, max_length=255, null=True)),
                ('zipCode', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedAddress', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='AddressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('state', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('zipCode', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Address')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='addressHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=1023, null=True)),
                ('question', models.CharField(db_index=True, max_length=1023, null=True)),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=1023, null=True)),
                ('question', models.CharField(db_index=True, editable=False, max_length=1023, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, max_length=1023, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedCommentPrompt', to='consentrecords.Transaction')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdCommentPrompt', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='CommentPromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, editable=False, max_length=1023, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.CommentPrompt')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentPromptHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DisqualifyingTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedDisqualifyingTag', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='DisqualifyingTagHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.DisqualifyingTag')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.CharField(db_index=True, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedEngagement', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='EngagementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Engagement')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='engagementHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedEnrollment', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Enrollment')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customOrganization', models.CharField(db_index=True, max_length=255, null=True)),
                ('customSite', models.CharField(db_index=True, max_length=255, null=True)),
                ('customOffering', models.CharField(db_index=True, max_length=255, null=True)),
                ('start', models.CharField(db_index=True, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, max_length=10, null=True)),
                ('timeframe', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperience', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperienceCustomService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceCustomService', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customService', to='consentrecords.Experience')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceCustomService', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperienceCustomServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperienceCustomService')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceCustomServiceHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customOrganization', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('customSite', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('customOffering', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('start', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('timeframe', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('stage', models.CharField(db_index=True, max_length=20, null=True)),
                ('timeframe', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePrompt', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperiencePromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('stage', models.CharField(db_index=True, editable=False, max_length=20, null=True)),
                ('timeframe', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencePromptService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePromptService', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptService', to='consentrecords.ExperiencePrompt')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperiencePromptServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperiencePromptService')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencePromptText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePromptText', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptText', to='consentrecords.ExperiencePrompt')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePromptText', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperiencePromptTextHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperiencePromptText')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptTextHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceService', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='consentrecords.Experience')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ExperienceServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperienceService')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroup', to='consentrecords.Transaction')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroup', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupMember', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='consentrecords.Group')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupMember', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='GroupMemberHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.GroupMember')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupMemberHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Group')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='GroupNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.GroupName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedInquiry', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='InquiryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Inquiry')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiryHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('isFresh', models.CharField(max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedNotification', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='NotificationArgument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('argument', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedNotificationArgument', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationArgument', to='consentrecords.Notification')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdNotificationArgument', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='NotificationArgumentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('argument', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.NotificationArgument')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationArgumentHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('isFresh', models.CharField(editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Notification')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, max_length=255, null=True)),
                ('minimumAge', models.CharField(db_index=True, max_length=255, null=True)),
                ('maximumAge', models.CharField(db_index=True, max_length=255, null=True)),
                ('minimumGrade', models.CharField(db_index=True, max_length=255, null=True)),
                ('maximumGrade', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOffering', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OfferingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('minimumAge', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('maximumAge', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('minimumGrade', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('maximumGrade', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Offering')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOfferingName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Offering')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOfferingName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OfferingNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OfferingName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOfferingService', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='consentrecords.Offering')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OfferingServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OfferingService')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, max_length=255, null=True)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganization', to='consentrecords.Transaction')),
                ('inquiryAccessGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizationInquiryAccessGroup', to='consentrecords.Group')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganization', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OrganizationGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationAccessGroup', to='consentrecords.Group')),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationGroupAccess', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccess', to='consentrecords.Organization')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationGroupAccess', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OrganizationGroupAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('accessee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupAccessHistory', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OrganizationGroupAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupAccessHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('publicAccess', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('inquiryAccessGroup', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizationInquiryAccessGroupHistory', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Organization')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Organization')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OrganizationNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OrganizationName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='OrganizationUserAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.CharField(db_index=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('specialAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('canAnswerExperience', models.CharField(max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPath', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='PathGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccess', to='consentrecords.Group')),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPathGroupAccess', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccess', to='consentrecords.Path')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPathGroupAccess', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='PathGroupAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('accessee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccessHistory', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.PathGroupAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccessHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PathHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('specialAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('canAnswerExperience', models.CharField(max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Path')),
            ],
        ),
        migrations.CreateModel(
            name='PathUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='PathUserAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(db_index=True, null=True)),
                ('startTime', models.CharField(db_index=True, max_length=10, null=True)),
                ('endTime', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPeriod', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='PeriodHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(db_index=True, editable=False, null=True)),
                ('startTime', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('endTime', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Period')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='periodHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(db_index=True, max_length=20, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedService', to='consentrecords.Transaction')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdService', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(db_index=True, editable=False, max_length=20, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceImplication', to='consentrecords.Transaction')),
                ('impliedService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impliedService', to='consentrecords.Service')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceImplication', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceImplication', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceImplicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impliedService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impliedServiceHistory', to='consentrecords.Service')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ServiceImplication')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceImplicationHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ServiceName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOfferingLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceOfferingLabel', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringLabel', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceOfferingLabel', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceOfferingLabelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ServiceOfferingLabel')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceOfferingLabelHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrganizationLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceOrganizationLabel', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationLabel', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceOrganizationLabel', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceOrganizationLabelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ServiceOrganizationLabel')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceOrganizationLabelHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSiteLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceSiteLabel', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteLabel', to='consentrecords.Service')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceSiteLabel', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='ServiceSiteLabelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ServiceSiteLabel')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceSiteLabelHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registrationDeadline', models.CharField(db_index=True, max_length=10, null=True)),
                ('start', models.CharField(db_index=True, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, max_length=10, null=True)),
                ('canRegister', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSession', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='consentrecords.Offering')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSession', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registrationDeadline', models.CharField(db_index=True, max_length=10, null=True)),
                ('start', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('end', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('canRegister', models.CharField(db_index=True, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Session')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessionHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SessionName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSessionName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Session')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSessionName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='SessionNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.SessionName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessionNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSite', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='consentrecords.Organization')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSite', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='SiteHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webSite', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Site')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSiteName', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='consentrecords.Site')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSiteName', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='SiteNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.SiteName')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteNameHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedStreet', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='street', to='consentrecords.Address')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdStreet', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='StreetHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(editable=False)),
                ('text', models.CharField(editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Street')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='streetHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_index=True, max_length=255, null=True)),
                ('lastName', models.CharField(db_index=True, max_length=255, null=True)),
                ('birthday', models.CharField(db_index=True, max_length=10, null=True)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUser', to='consentrecords.Transaction')),
                ('primaryAdministrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUser', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserEmail', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserEmail', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=255, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.UserEmail')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userEmailHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccessGroup', to='consentrecords.Group')),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserGroupAccess', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccess', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserGroupAccess', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='UserGroupAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('accessee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessGroupHistory', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.UserGroupAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userGroupAccessHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(editable=False, max_length=255, null=True)),
                ('lastName', models.CharField(editable=False, max_length=255, null=True)),
                ('birthday', models.CharField(editable=False, max_length=10, null=True)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.User')),
                ('primaryAdministrator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccessUser', to='consentrecords.User')),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserUserAccess', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccess', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserUserAccess', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='UserUserAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('accessee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessUserHistory', to='consentrecords.User')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.UserUserAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserUserAccessHistory', to='consentrecords.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='consentrecords.Session'),
        ),
        migrations.AddField(
            model_name='period',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPeriod', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathuseraccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathUserAccessHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='pathuseraccesshistory',
            name='instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.PathUserAccess'),
        ),
        migrations.AddField(
            model_name='pathuseraccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PathUserAccessHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathuseraccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathUserAccess', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='pathuseraccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPathUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathuseraccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccess', to='consentrecords.Path'),
        ),
        migrations.AddField(
            model_name='pathuseraccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPathUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathhistory',
            name='primaryAdministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredPathHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='pathhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='path',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='path',
            name='primaryAdministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredPath', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='path',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPath', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationuseraccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationUserAccessHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='organizationuseraccesshistory',
            name='instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OrganizationUserAccess'),
        ),
        migrations.AddField(
            model_name='organizationuseraccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationUserAccessHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationuseraccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationAccessUser', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='organizationuseraccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationuseraccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccess', to='consentrecords.Organization'),
        ),
        migrations.AddField(
            model_name='organizationuseraccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offeringservicehistory',
            name='service',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringServiceHistory', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='offeringservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringServiceHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offeringservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeringService', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='offeringservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOfferingService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offering',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offering', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='offering',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOffering', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdNotification', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='inquiryhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiryHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='consentrecords.Session'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdInquiry', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='groupmemberhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupMemberHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMember', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='experienceservicehistory',
            name='service',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceServiceHistory', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experienceservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceServiceHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceService', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experienceservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencepromptservicehistory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServiceHistory', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experiencepromptservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServiceHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencepromptservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptService', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experiencepromptservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePromptService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='domain',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptDomainHistory', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='offering',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistory', to='consentrecords.Offering'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistory', to='consentrecords.Organization'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistory', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='experienceprompthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptDomain', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompt', to='consentrecords.Offering'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompt', to='consentrecords.Organization'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompt', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePrompt', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencehistory',
            name='offering',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistory', to='consentrecords.Offering'),
        ),
        migrations.AddField(
            model_name='experiencehistory',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistory', to='consentrecords.Organization'),
        ),
        migrations.AddField(
            model_name='experiencehistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistory', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='experiencehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experience',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='consentrecords.Offering'),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='consentrecords.Organization'),
        ),
        migrations.AddField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='consentrecords.Path'),
        ),
        migrations.AddField(
            model_name='experience',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='experience',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperience', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentUserHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='consentrecords.Session'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdEnrollment', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentUser', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='engagementhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagementUserHistory', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='consentrecords.Session'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdEngagement', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagementUser', to='consentrecords.User'),
        ),
        migrations.AddField(
            model_name='disqualifyingtaghistory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTagHistory', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='disqualifyingtaghistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTagHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='disqualifyingtag',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTag', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AddField(
            model_name='disqualifyingtag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTag', to='consentrecords.Service'),
        ),
        migrations.AddField(
            model_name='disqualifyingtag',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdDisqualifyingTag', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='asker',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='askedCommentHistory', to='consentrecords.Path'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.Comment'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentHistory', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askedComment', to='consentrecords.Path'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedComment', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='consentrecords.Experience'),
        ),
        migrations.AddField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdComment', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='address',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='consentrecords.Site'),
        ),
        migrations.AddField(
            model_name='address',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdAddress', to='consentrecords.Transaction'),
        ),
    ]
