# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0046_auto_20170523_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailhistory',
            name='position',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
