# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:03
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0047_auto_20170523_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUserAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccessRequestUser', to='consentrecords.User')),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserUserAccessRequest', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessRequest', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserUserAccessRequest', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='UserUserAccessRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessRequestUserHistory', to='consentrecords.User')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.UserUserAccessRequest')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserUserAccessRequestHistory', to='consentrecords.Transaction')),
            ],
        ),
    ]
