# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0048_useruseraccessrequest_useruseraccessrequesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedAddress', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedComment', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='commentprompt',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedCommentPrompt', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='disqualifyingtag',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedDisqualifyingTag', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedEngagement', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedEnrollment', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experience',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperience', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencecustomservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceCustomService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceprompt',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePrompt', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencepromptservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePromptService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceprompttext',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePromptText', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupMember', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='groupname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedInquiry', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedNotification', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='notificationargument',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedNotificationArgument', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offering',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOffering', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offeringname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOfferingName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='offeringservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOfferingService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganization', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationgroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationGroupAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='organizationuseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='path',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPath', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathgroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPathGroupAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='pathuseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPathUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='period',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPeriod', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='service',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedService', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='serviceimplication',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceImplication', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='serviceofferinglabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceOfferingLabel', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='serviceorganizationlabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceOrganizationLabel', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='servicesitelabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceSiteLabel', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='session',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSession', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='sessionname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSessionName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='site',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSite', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='sitename',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSiteName', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='street',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedStreet', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUser', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='usergroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserGroupAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='useruseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserUserAccess', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='useruseraccessrequest',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserUserAccessRequest', to='consentrecords.Transaction'),
        ),
    ]
