# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0049_auto_20170523_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserEmail', to='consentrecords.Transaction'),
        ),
    ]
