# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0050_useremail_lasttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(default='009161d3-5539-45e6-bf00-d80254734f77', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='consentrecords.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedAddresses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedAddresses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='address',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='address',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdAddresses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='addressHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askedComments', to='consentrecords.Path'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedComments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedComments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='consentrecords.Experience'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdComments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='commenthistory',
            name='asker',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='askedCommentHistories', to='consentrecords.Path'),
        ),
        migrations.AlterField(
            model_name='commenthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='commentprompt',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedCommentPrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='commentprompt',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedCommentPrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='commentprompt',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdCommentPrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='commentprompthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentPromptHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtag',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedDisqualifyingTags', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtag',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedDisqualifyingTags', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtag',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTags', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTags', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtag',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdDisqualifyingTags', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtaghistory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTagHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='disqualifyingtaghistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='disqualifyingTagHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedEngagements', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedEngagements', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='consentrecords.Session'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdEngagements', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEngagements', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='engagementhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='engagementHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='engagementhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEngagementHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedEnrollments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedEnrollments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='consentrecords.Session'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdEnrollments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEnrollments', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEnrollmentHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiences', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiences', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='consentrecords.Path'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiences', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencecustomservice',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceCustomServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencecustomservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceCustomServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencecustomservice',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customServices', to='consentrecords.Experience'),
        ),
        migrations.AlterField(
            model_name='experiencecustomservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceCustomServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencecustomservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceCustomServiceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencehistory',
            name='offering',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistories', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='experiencehistory',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistories', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='experiencehistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistories', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='experiencehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainExperiencePrompts', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompts', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompts', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePrompts', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='experienceprompt',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePrompts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='domain',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptDomainHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='offering',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistories', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistories', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistories', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePromptServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePromptServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServices', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServices', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePromptServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservicehistory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServiceHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experiencepromptservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptServiceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompttext',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperiencePromptTexts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompttext',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperiencePromptTexts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompttext',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptTexts', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AlterField(
            model_name='experienceprompttext',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperiencePromptTexts', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceprompttexthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptTextHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceservice',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceservice',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consentrecords.Experience'),
        ),
        migrations.AlterField(
            model_name='experienceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceServices', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experienceservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='experienceservicehistory',
            name='service',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceServiceHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experienceservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceServiceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroups', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='group',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroups', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupMembers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupMembers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupMembers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMembers', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='groupmemberhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupMemberHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupmemberhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupMemberHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupnamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedInquiries', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedInquiries', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='consentrecords.Session'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdInquiries', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='inquiryhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiryHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='inquiryhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiryHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedNotifications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedNotifications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdNotifications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notificationargument',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedNotificationArguments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notificationargument',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedNotificationArguments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notificationargument',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationArguments', to='consentrecords.Notification'),
        ),
        migrations.AlterField(
            model_name='notificationargument',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdNotificationArguments', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notificationargumenthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationArgumentHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notificationHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOfferings', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOfferings', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOfferings', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringname',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOfferingNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOfferingNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringname',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='offeringname',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOfferingNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringnamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringservice',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOfferingServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringservice',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOfferingServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringservice',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='offeringservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeringServices', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='offeringservice',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOfferingServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='offeringservicehistory',
            name='service',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringServiceHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='offeringservicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringServiceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizations', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inquiryAccessGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiryAccessGroupOrganizations', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizations', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizations', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupAccesses', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccesses', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupAccessHistories', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='organizationgroupaccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationhistory',
            name='inquiryAccessGroup',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InquiryAccessGroupOrganizationHistories', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='organizationhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationnamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationUserAccesses', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccesses', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationUserAccessHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='organizationuseraccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationUserAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='path',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPaths', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='path',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPaths', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='path',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='path',
            name='primaryAdministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredPaths', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='path',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPaths', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccesses', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPathGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPathGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccesses', to='consentrecords.Path'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPathGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccessHistories', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='pathgroupaccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathGroupAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathhistory',
            name='primaryAdministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredPathHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='pathhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathuseraccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathUserAccesses', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='pathuseraccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPathUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathuseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPathUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathuseraccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccesses', to='consentrecords.Path'),
        ),
        migrations.AlterField(
            model_name='pathuseraccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPathUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='pathuseraccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pathUserAccessHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='pathuseraccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PathUserAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='period',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedPeriods', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='period',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedPeriods', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='period',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='consentrecords.Session'),
        ),
        migrations.AlterField(
            model_name='period',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdPeriods', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='periodhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='periodHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='service',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='service',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServices', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceimplication',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceImplications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceimplication',
            name='impliedService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impliedServiceImplications', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='serviceimplication',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceImplications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceimplication',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceImplications', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='serviceimplication',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceImplications', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceimplicationhistory',
            name='impliedService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impliedServiceHistories', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='serviceimplicationhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceImplicationHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicenamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceofferinglabel',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceOfferingLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceofferinglabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceOfferingLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceofferinglabel',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offeringLabels', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='serviceofferinglabel',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceOfferingLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceofferinglabelhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceOfferingLabelHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceorganizationlabel',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceOrganizationLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceorganizationlabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceOrganizationLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceorganizationlabel',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationLabels', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='serviceorganizationlabel',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceOrganizationLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='serviceorganizationlabelhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceOrganizationLabelHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicesitelabel',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedServiceSiteLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicesitelabel',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedServiceSiteLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicesitelabel',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteLabels', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='servicesitelabel',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdServiceSiteLabels', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='servicesitelabelhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='serviceSiteLabelHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='session',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSessions', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='session',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSessions', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='session',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='consentrecords.Offering'),
        ),
        migrations.AlterField(
            model_name='session',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSessions', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessionHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sessionname',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSessionNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sessionname',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSessionNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sessionname',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Session'),
        ),
        migrations.AlterField(
            model_name='sessionname',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSessionNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sessionnamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessionNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='site',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSites', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='site',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSites', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='site',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSites', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sitehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedSiteNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedSiteNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='consentrecords.Site'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdSiteNames', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='sitenamehistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='siteNameHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='street',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedStreets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='street',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedStreets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='street',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='consentrecords.Address'),
        ),
        migrations.AlterField(
            model_name='street',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdStreets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='streethistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='streetHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUsers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUsers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primaryAdministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredUsers', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUsers', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserEmails', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserEmails', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserEmails', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useremailhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userEmailHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergroupaccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGroupAccesses', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='usergroupaccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergroupaccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergroupaccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccesses', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='usergroupaccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserGroupAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergroupaccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessGroupHistories', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='usergroupaccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userGroupAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='primaryAdministrator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredUserHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccess',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userUserAccesses', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccess',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccess',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccess',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccesses', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccess',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserUserAccesses', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccesshistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessUserHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccesshistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserUserAccessHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequest',
            name='accessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userUserAccessRequests', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequest',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserUserAccessRequests', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequest',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserUserAccessRequests', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequest',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessRequests', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequest',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserUserAccessRequests', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequesthistory',
            name='accessee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userUserAccessRequestHistories', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='useruseraccessrequesthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserUserAccessRequestHistories', to='consentrecords.Transaction'),
        ),
    ]
