# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0051_auto_20170525_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceprompt',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domainExperiencePrompts', to='consentrecords.Service'),
        ),
        migrations.AlterField(
            model_name='experienceprompthistory',
            name='domain',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencePromptDomainHistories', to='consentrecords.Service'),
        ),
    ]
