# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:50
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0052_auto_20170528_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPromptText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=1023, null=True)),
                ('languageCode', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedCommentPromptTexts', to='consentrecords.Transaction')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedCommentPromptTexts', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.IInstance),
        ),
        migrations.CreateModel(
            name='CommentPromptTextHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, editable=False, max_length=1023, null=True)),
                ('languageCode', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.CommentPromptText')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentPromptTextHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentprompt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='commentprompthistory',
            name='question',
        ),
        migrations.AddField(
            model_name='commentprompttext',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='consentrecords.CommentPrompt'),
        ),
        migrations.AddField(
            model_name='commentprompttext',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdCommentPromptTexts', to='consentrecords.Transaction'),
        ),
    ]
