# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0053_auto_20170528_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationargument',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationargumenthistory',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
