# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0054_auto_20170529_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecustomservice',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencecustomservicehistory',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceservice',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceservicehistory',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
