# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0057_auto_20170530_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='consentrecords.Group'),
        ),
    ]
