# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:50
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0058_auto_20170531_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedAccessSources', to='consentrecords.Transaction')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedAccessSources', to='consentrecords.Transaction')),
                ('primaryAdministrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdAccessSources', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AccessSourceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicAccess', models.CharField(db_index=True, max_length=10, null=True)),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.AccessSource')),
                ('primaryAdministrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administeredHistories', to='consentrecords.User')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accessSourceHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupAccesses', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantees', to='consentrecords.Group')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupAccesses', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccesses', to='consentrecords.AccessSource')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupAccesses', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.Grant),
        ),
        migrations.CreateModel(
            name='GroupAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='granteeHistories', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.GroupAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupAccessHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserAccesses', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantees', to='consentrecords.User')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserAccesses', to='consentrecords.Transaction')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccesses', to='consentrecords.AccessSource')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserAccesses', to='consentrecords.Transaction')),
            ],
            bases=(models.Model, consentrecords.models.Grant),
        ),
        migrations.CreateModel(
            name='UserAccessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='granteeHistories', to='consentrecords.User')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.UserAccess')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userAccessHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.AlterField(
            model_name='experiencepromptservice',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consentrecords.ExperiencePrompt'),
        ),
        migrations.AlterField(
            model_name='experienceprompttext',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='consentrecords.ExperiencePrompt'),
        ),
    ]
