# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0059_auto_20170605_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='publicAccess',
        ),
        migrations.RemoveField(
            model_name='organizationhistory',
            name='publicAccess',
        ),
        migrations.RemoveField(
            model_name='path',
            name='primaryAdministrator',
        ),
        migrations.RemoveField(
            model_name='path',
            name='publicAccess',
        ),
        migrations.RemoveField(
            model_name='pathhistory',
            name='primaryAdministrator',
        ),
        migrations.RemoveField(
            model_name='pathhistory',
            name='publicAccess',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='primaryAdministrator',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='publicAccess',
        ),
        migrations.AddField(
            model_name='path',
            name='accessSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='consentrecords.AccessSource'),
        ),
    ]
