# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0061_auto_20170606_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruseraccessrequest',
            old_name='accessee',
            new_name='grantee',
        ),
        migrations.RenameField(
            model_name='useruseraccessrequesthistory',
            old_name='accessee',
            new_name='grantee',
        ),
    ]
