# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0065_auto_20170608_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessSource',
            new_name='GrantTarget',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
    ]
