# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0066_auto_20170613_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessSourceHistory',
            new_name='GrantTargetHistory',
        ),
    ]
