# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0067_auto_20170613_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAccess',
            new_name='GroupGrant',
        ),
        migrations.RenameModel(
            old_name='GroupAccessHistory',
            new_name='GroupGrantHistory',
        ),
        migrations.RenameModel(
            old_name='UserAccess',
            new_name='UserGrant',
        ),
        migrations.RenameModel(
            old_name='UserAccessHistory',
            new_name='UserGrantHistory',
        ),
    ]
