# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0068_auto_20170613_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='accessSource',
            new_name='grantTarget',
        ),
        migrations.AlterField(
            model_name='granttarget',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGrantTargets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='granttarget',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGrantTargets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='granttarget',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGrantTargets', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='granttargethistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='grantTargetHistories', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedGroupGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedGroupGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupGrants', to='consentrecords.GrantTarget'),
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdGroupGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='deleteTransaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedUserGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedUserGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='parent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userGrants', to='consentrecords.GrantTarget'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdUserGrants', to='consentrecords.Transaction'),
        ),
        migrations.AlterField(
            model_name='usergranthistory',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userGrantHistories', to='consentrecords.Transaction'),
        ),
    ]
