# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0069_auto_20170613_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUserAccessRequest',
            new_name='UserUserGrantRequest',
        ),
        migrations.RenameModel(
            old_name='UserUserAccessRequestHistory',
            new_name='UserUserGrantRequestHistory',
        ),
    ]
