# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0071_auto_20170613_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencepromptservice',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
