# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0073_experiencepromptservicehistory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='service',
            field=models.ManyToManyField(related_name='offering', through='consentrecords.OfferingService', to='consentrecords.Service'),
        ),
    ]
