# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0074_offering_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='implication',
            field=models.ManyToManyField(related_name='implyingService', through='consentrecords.ServiceImplication', to='consentrecords.Service'),
        ),
    ]
