# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0075_service_implication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceImplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceImplications', to='consentrecords.Experience')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceImplications', to='consentrecords.Service')),
            ],
        ),
    ]
