# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0077_auto_20170719_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgrant',
            name='grantor_id',
            field=models.UUIDField(db_index=True, default='12345678901234567890123456789012', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergrant',
            name='grantor_id',
            field=models.UUIDField(db_index=True, default='12345678901234567890123456789012', editable=False),
            preserve_default=False,
        ),
    ]
