# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0079_auto_20170719_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granttarget',
            name='deleteTransaction',
        ),
        migrations.RemoveField(
            model_name='granttarget',
            name='lastTransaction',
        ),
        migrations.RemoveField(
            model_name='granttarget',
            name='primaryAdministrator',
        ),
        migrations.RemoveField(
            model_name='granttarget',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='granttargethistory',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='granttargethistory',
            name='primaryAdministrator',
        ),
        migrations.RemoveField(
            model_name='granttargethistory',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='groupgrant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='usergrant',
            name='parent',
        ),
        migrations.DeleteModel(
            name='GrantTarget',
        ),
        migrations.DeleteModel(
            name='GrantTargetHistory',
        ),
    ]
