# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 18:21
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0081_auto_20170905_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroupGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationGroupGrants', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationGrantees', to='consentrecords.Group')),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupGrants', to='consentrecords.Organization')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationGroupGrants', to='consentrecords.Transaction')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationGroupGrants', to='consentrecords.Transaction')),
            ],
            bases=(consentrecords.models.Grant, consentrecords.models.OrganizationGrant, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationGroupGrantHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGranteeHistories', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OrganizationGroupGrant')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupGrantHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUserGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, max_length=10, null=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedOrganizationUserGrants', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationGrantees', to='consentrecords.User')),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGrants', to='consentrecords.Organization')),
                ('lastTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedOrganizationUserGrants', to='consentrecords.Transaction')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdOrganizationUserGrants', to='consentrecords.Transaction')),
            ],
            bases=(consentrecords.models.Grant, consentrecords.models.OrganizationGrant, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationUserGrantHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privilege', models.CharField(db_index=True, editable=False, max_length=10, null=True)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationGranteeHistories', to='consentrecords.User')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.OrganizationUserGrant')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizationUserGrantHistories', to='consentrecords.Transaction')),
            ],
        ),
    ]
