# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0082_organizationgroupgrant_organizationgroupgranthistory_organizationusergrant_organizationusergranthist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupGrantHistory',
            new_name='UserGroupGrantHistory',
        ),
        migrations.RenameModel(
            old_name='UserGrantHistory',
            new_name='UserUserGrantHistory',
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGroupGrantees', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='groupgrant',
            name='grantor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupGrants', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='organizationgroupgrant',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupGrants', to='consentrecords.Organization'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userUserGrantees', to='consentrecords.User'),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='grantor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGrants', to='consentrecords.User'),
        ),
    ]
