# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0083_auto_20170923_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupgrant',
            old_name='grantor_id',
            new_name='grantor',
        ),
        migrations.RenameField(
            model_name='usergrant',
            old_name='grantor_id',
            new_name='grantor',
        ),
        migrations.AlterField(
            model_name='organizationgroupgrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationGroupGrantees', to='consentrecords.Group'),
        ),
        migrations.AlterField(
            model_name='organizationusergrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationUserGrantees', to='consentrecords.User'),
        ),
    ]
