# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0087_auto_20171201_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='tipLevel',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
