# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 16:32
from __future__ import unicode_literals

import consentrecords.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consentrecords', '0089_auto_20180123_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceGroupGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.IntegerField(db_index=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceGroupGrants', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceGroupGrantees', to='consentrecords.Group')),
            ],
            bases=(consentrecords.models.Grant, models.Model),
        ),
        migrations.CreateModel(
            name='ExperienceGroupGrantHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.IntegerField(db_index=True, editable=False)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceGranteeHistories', to='consentrecords.Group')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperienceGroupGrant')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceGroupGrantHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceUserGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.IntegerField(db_index=True)),
                ('deleteTransaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedExperienceUserGrants', to='consentrecords.Transaction')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceUserGrantees', to='consentrecords.User')),
            ],
            bases=(consentrecords.models.Grant, models.Model),
        ),
        migrations.CreateModel(
            name='ExperienceUserGrantHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.IntegerField(db_index=True, editable=False)),
                ('grantee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceGranteeHistories', to='consentrecords.User')),
                ('instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consentrecords.ExperienceUserGrant')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='experienceUserGrantHistories', to='consentrecords.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='isHidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='experienceusergrant',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGrants', to='consentrecords.Experience'),
        ),
        migrations.AddField(
            model_name='experienceusergrant',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceUserGrants', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experienceusergrant',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceUserGrants', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencegroupgrant',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupGrants', to='consentrecords.Experience'),
        ),
        migrations.AddField(
            model_name='experiencegroupgrant',
            name='lastTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changedExperienceGroupGrants', to='consentrecords.Transaction'),
        ),
        migrations.AddField(
            model_name='experiencegroupgrant',
            name='transaction',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='createdExperienceGroupGrants', to='consentrecords.Transaction'),
        ),
    ]
